/*
---
keep: false
---
Generated by /Users/nielsgregersjohansen/kitchens/365admin-publish/scaffold/25-generatedatabase.ps1
Do not edit this file manually
*/

--drop schema if exists "proc" cascade;

--CREATE SCHEMA if not exists "proc";
{{ template "tool_create_proc.sql".}} 
{{ template "tool_update_proc.sql".}} {{ template "tool_patch_proc.sql".}} 
{{ template "tool_delete_proc.sql".}} 
{{ template "tool_undo_delete_proc.sql".}} 
{{ template "region_create_proc.sql".}} 
{{ template "region_update_proc.sql".}} {{ template "region_patch_proc.sql".}} 
{{ template "region_delete_proc.sql".}} 
{{ template "region_undo_delete_proc.sql".}} 
{{ template "country_create_proc.sql".}} 
{{ template "country_update_proc.sql".}} {{ template "country_patch_proc.sql".}} 
{{ template "country_delete_proc.sql".}} 
{{ template "country_undo_delete_proc.sql".}} 
{{ template "userprofile_create_proc.sql".}} 
{{ template "userprofile_update_proc.sql".}} {{ template "userprofile_patch_proc.sql".}} 
{{ template "userprofile_delete_proc.sql".}} 
{{ template "userprofile_undo_delete_proc.sql".}} 
{{ template "language_create_proc.sql".}} 
{{ template "language_update_proc.sql".}} {{ template "language_patch_proc.sql".}} 
{{ template "language_delete_proc.sql".}} 
{{ template "language_undo_delete_proc.sql".}} 
{{ template "purpose_create_proc.sql".}} 
{{ template "purpose_update_proc.sql".}} {{ template "purpose_patch_proc.sql".}} 
{{ template "purpose_delete_proc.sql".}} 
{{ template "purpose_undo_delete_proc.sql".}} 
{{ template "toolgroup_create_proc.sql".}} 
{{ template "toolgroup_update_proc.sql".}} {{ template "toolgroup_patch_proc.sql".}} 
{{ template "toolgroup_delete_proc.sql".}} 
{{ template "toolgroup_undo_delete_proc.sql".}} 
{{ template "event_create_proc.sql".}} 
{{ template "event_update_proc.sql".}} {{ template "event_patch_proc.sql".}} 
{{ template "event_delete_proc.sql".}} 
{{ template "event_undo_delete_proc.sql".}} 
{{ template "auditlog_create_proc.sql".}} 
{{ template "auditlog_update_proc.sql".}} {{ template "auditlog_patch_proc.sql".}} 
{{ template "auditlog_delete_proc.sql".}} 
{{ template "auditlog_undo_delete_proc.sql".}} 
{{ template "category_create_proc.sql".}} 
{{ template "category_update_proc.sql".}} {{ template "category_patch_proc.sql".}} 
{{ template "category_delete_proc.sql".}} 
{{ template "category_undo_delete_proc.sql".}} 
{{ template "userrole_create_proc.sql".}} 
{{ template "userrole_update_proc.sql".}} {{ template "userrole_patch_proc.sql".}} 
{{ template "userrole_delete_proc.sql".}} 
{{ template "userrole_undo_delete_proc.sql".}} 
{{ template "accesspoint_create_proc.sql".}} 
{{ template "accesspoint_update_proc.sql".}} {{ template "accesspoint_patch_proc.sql".}} 
{{ template "accesspoint_delete_proc.sql".}} 
{{ template "accesspoint_undo_delete_proc.sql".}} 
{{ template "usergroup_create_proc.sql".}} 
{{ template "usergroup_update_proc.sql".}} {{ template "usergroup_patch_proc.sql".}} 
{{ template "usergroup_delete_proc.sql".}} 
{{ template "usergroup_undo_delete_proc.sql".}} 
{{ template "importdata_create_proc.sql".}} 
{{ template "importdata_update_proc.sql".}} {{ template "importdata_patch_proc.sql".}} 
{{ template "importdata_delete_proc.sql".}} 
{{ template "importdata_undo_delete_proc.sql".}} 

