name: "Task Request"
description: "Submit a request for a artifact ."
title: "[Task]: "
type: Task

assignees: []
body:
- type: dropdown
  id: type
  attributes:
    label: Type of artifact?
    options:
      - API
      - Page
      - Component

- type: textarea
  id: behaviour
  attributes:
    label: Behaviour
    description: "High  level description of the expected flow."
    value: |
      1.
      2.
      3.
      ...
    render: bash
  validations:
    required: true      

