"use client";
import { Tool } from "@/app/tools/api/view/schemas";

// Mock data
export const mockTools: Tool[] = [

  {
    id: 2,
    name: "Slack",
    description: "Business communication platform",
    url: "https://slack.com",
    groupId: "group1",
    purposes: [
      { id: "purpose3", value: "Messaging", order: "1" },
      { id: "purpose4", value: "Team Collaboration", order: "2" },
    ],
    tags: [
      { id: "tag3", value: "Chat", order: "1", color: "#611F69" },
      { id: "tag4", value: "Productivity", order: "2", color: "#611F69" },
    ],
    version: "4.20.0",
    status: "active",
    icon: "https://cdn.iconscout.com/icon/free/png-256/slack-226533.png",
    documentationUrl: "https://slack.com/help",
    supportContact: [{ id: "email", value: "feedback@slack.com", order: "1" }],
    license: [{ id: "freemium", value: "Freemium", order: "1" }],
    compatiblePlatforms: ["Windows", "macOS", "iOS", "Android", "Web"],
    systemRequirements: "Modern web browser",
    countries: [{ id: "country2", value: "Global", order: "1" }],
    repositoryUrl: "https://github.com/slackapi",
    collaborationType: [{ id: "type2", value: "Cloud-Based", order: "1" }],
    documents: [{ name: "API Documentation", url: "https://api.slack.com/docs" }],
    teamSize: 1000,
    primaryFocus: [{ id: "focus2", value: "Business Communication", order: "1" }],
    createdAt: new Date(),
    createdBy: "Admin",
    updatedAt: new Date(),
    updatedBy: "Admin",
    deletedAt: null,
    deletedBy: null,
  },

  {
    id: 4,
    name: "Trello",
    description: "Project management tool using boards and cards",
    url: "https://trello.com",
    groupId: "group2",
    purposes: [
      { id: "purpose7", value: "Project Management", order: "1" },
      { id: "purpose8", value: "Task Tracking", order: "2" },
    ],
    tags: [
      { id: "tag7", value: "Organization", order: "1", color: "#0079BF" },
      { id: "tag8", value: "Productivity", order: "2", color: "#0079BF" },
    ],
    version: "2021.10",
    status: "active",
    icon: "https://cdn.iconscout.com/icon/free/png-256/trello-6-569395.png",
    documentationUrl: "https://help.trello.com",
    supportContact: [{ id: "email", value: "support@trello.com", order: "1" }],
    license: [{ id: "freemium", value: "Freemium", order: "1" }],
    compatiblePlatforms: ["Web", "iOS", "Android"],
    systemRequirements: "Modern web browser",
    countries: [{ id: "country2", value: "Global", order: "1" }],
    repositoryUrl: "",
    collaborationType: [{ id: "type2", value: "Cloud-Based", order: "1" }],
    documents: [{ name: "Getting Started Guide", url: "https://example.com/trello-guide.pdf" }],
    teamSize: 300,
    primaryFocus: [{ id: "focus4", value: "Project Management", order: "1" }],
    createdAt: new Date(),
    createdBy: "Admin",
    updatedAt: new Date(),
    updatedBy: "Admin",
    deletedAt: null,
    deletedBy: null,
  },
  {
    id: 5,
    name: "Asana",
    description: "Work management platform for teams",
    url: "https://asana.com",
    groupId: "group2",
    purposes: [
      { id: "purpose9", value: "Task Management", order: "1" },
      { id: "purpose10", value: "Project Tracking", order: "2" },
    ],
    tags: [
      { id: "tag9", value: "Productivity", order: "1", color: "#FC636B" },
      { id: "tag10", value: "Collaboration", order: "2", color: "#FC636B" },
    ],
    version: "2021.09",
    status: "active",
    icon: "https://cdn.iconscout.com/icon/free/png-256/asana-4-569455.png",
    documentationUrl: "https://asana.com/guide",
    supportContact: [{ id: "email", value: "support@asana.com", order: "1" }],
    license: [{ id: "freemium", value: "Freemium", order: "1" }],
    compatiblePlatforms: ["Web", "iOS", "Android"],
    systemRequirements: "Modern web browser",
    countries: [{ id: "country2", value: "Global", order: "1" }],
    repositoryUrl: "",
    collaborationType: [{ id: "type2", value: "Cloud-Based", order: "1" }],
    documents: [{ name: "User Guide", url: "https://example.com/asana-user-guide.pdf" }],
    teamSize: 400,
    primaryFocus: [{ id: "focus5", value: "Task Management", order: "1" }],
    createdAt: new Date(),
    createdBy: "Admin",
    updatedAt: new Date(),
    updatedBy: "Admin",
    deletedAt: null,
    deletedBy: null,
  },
  // Continue adding more items up to id:30
  {
    id: 6,
    name: "Jira",
    description: "Issue and project tracking software",
    url: "https://www.atlassian.com/software/jira",
    groupId: "group3",
    purposes: [
      { id: "purpose11", value: "Issue Tracking", order: "1" },
      { id: "purpose12", value: "Agile Development", order: "2" },
    ],
    tags: [
      { id: "tag11", value: "Development", order: "1", color: "#0052CC" },
      { id: "tag12", value: "Agile", order: "2", color: "#0052CC" },
    ],
    version: "8.17.0",
    status: "active",
    icon: "https://cdn.iconscout.com/icon/free/png-256/jira-3628861-3030006.png",
    documentationUrl: "https://confluence.atlassian.com/jirasoftwarecloud",
    supportContact: [{ id: "email", value: "support@atlassian.com", order: "1" }],
    license: [{ id: "commercial", value: "Commercial", order: "1" }],
    compatiblePlatforms: ["Web", "iOS", "Android"],
    systemRequirements: "Modern web browser",
    countries: [{ id: "country2", value: "Global", order: "1" }],
    repositoryUrl: "",
    collaborationType: [{ id: "type2", value: "Cloud-Based", order: "1" }],
    documents: [{ name: "Administrator's Guide", url: "https://example.com/jira-admin-guide.pdf" }],
    teamSize: 600,
    primaryFocus: [{ id: "focus6", value: "Issue Tracking", order: "1" }],
    createdAt: new Date(),
    createdBy: "Admin",
    updatedAt: new Date(),
    updatedBy: "Admin",
    deletedAt: null,
    deletedBy: null,
  },
  {
    id: 7,
    name: "GitHub",
    description: "Code hosting platform for version control and collaboration",
    url: "https://github.com",
    groupId: "group3",
    purposes: [
      { id: "purpose13", value: "Version Control", order: "1" },
      { id: "purpose14", value: "Collaboration", order: "2" },
    ],
    tags: [
      { id: "tag13", value: "Code", order: "1", color: "#181717" },
      { id: "tag14", value: "Development", order: "2", color: "#181717" },
    ],
    version: "N/A",
    status: "active",
    icon: "https://cdn.iconscout.com/icon/free/png-256/github-170-1175028.png",
    documentationUrl: "https://docs.github.com",
    supportContact: [{ id: "email", value: "support@github.com", order: "1" }],
    license: [{ id: "freemium", value: "Freemium", order: "1" }],
    compatiblePlatforms: ["Web"],
    systemRequirements: "Modern web browser",
    countries: [{ id: "country2", value: "Global", order: "1" }],
    repositoryUrl: "https://github.com",
    collaborationType: [{ id: "type2", value: "Cloud-Based", order: "1" }],
    documents: [{ name: "Getting Started", url: "https://example.com/github-getting-started.pdf" }],
    teamSize: 10000,
    primaryFocus: [{ id: "focus7", value: "Code Hosting", order: "1" }],
    createdAt: new Date(),
    createdBy: "Admin",
    updatedAt: new Date(),
    updatedBy: "Admin",
    deletedAt: null,
    deletedBy: null,
  },
  // ... Continue adding items until id:30
  {
    id: 8,
    name: "GitLab",
    description: "A complete DevOps platform",
    url: "https://gitlab.com",
    groupId: "group3",
    purposes: [
      { id: "purpose15", value: "Version Control", order: "1" },
      { id: "purpose16", value: "Continuous Integration", order: "2" },
    ],
    tags: [
      { id: "tag15", value: "DevOps", order: "1", color: "#FC6D26" },
      { id: "tag16", value: "Collaboration", order: "2", color: "#FC6D26" },
    ],
    version: "14.3",
    status: "active",
    icon: "https://cdn.iconscout.com/icon/free/png-256/gitlab-282507.png",
    documentationUrl: "https://docs.gitlab.com",
    supportContact: [{ id: "email", value: "support@gitlab.com", order: "1" }],
    license: [{ id: "open-source", value: "Open Source", order: "1" }],
    compatiblePlatforms: ["Web"],
    systemRequirements: "Modern web browser",
    countries: [{ id: "country2", value: "Global", order: "1" }],
    repositoryUrl: "https://gitlab.com",
    collaborationType: [{ id: "type2", value: "Cloud-Based", order: "1" }],
    documents: [{ name: "Installation Guide", url: "https://example.com/gitlab-install-guide.pdf" }],
    teamSize: 5000,
    primaryFocus: [{ id: "focus8", value: "DevOps", order: "1" }],
    createdAt: new Date(),
    createdBy: "Admin",
    updatedAt: new Date(),
    updatedBy: "Admin",
    deletedAt: null,
    deletedBy: null,
  },
  // ... Continue adding items until id:30
  // For brevity, assume that items 9 through 29 are added here with similar structure.
  {
    id: 30,
    name: "Adobe Illustrator",
    description: "Vector graphics editor and design program",
    url: "https://www.adobe.com/products/illustrator.html",
    groupId: "group5",
    purposes: [
      { id: "purpose59", value: "Graphic Design", order: "1" },
      { id: "purpose60", value: "Vector Illustration", order: "2" },
    ],
    tags: [
      { id: "tag59", value: "Design", order: "1", color: "#FF9A00" },
      { id: "tag60", value: "Creative", order: "2", color: "#FF9A00" },
    ],
    version: "2021",
    status: "active",
    icon: "https://cdn.iconscout.com/icon/free/png-256/adobe-illustrator-cc-569308.png",
    documentationUrl: "https://helpx.adobe.com/illustrator/user-guide.html",
    supportContact: [{ id: "email", value: "support@adobe.com", order: "1" }],
    license: [{ id: "commercial", value: "Commercial", order: "1" }],
    compatiblePlatforms: ["Windows", "macOS"],
    systemRequirements: "Windows 10, macOS 10.15 or later",
    countries: [{ id: "country2", value: "Global", order: "1" }],
    repositoryUrl: "",
    collaborationType: [{ id: "type3", value: "Desktop Application", order: "1" }],
    documents: [{ name: "User Guide", url: "https://example.com/illustrator-user-guide.pdf" }],
    teamSize: 1500,
    primaryFocus: [{ id: "focus15", value: "Graphic Design", order: "1" }],
    createdAt: new Date(),
    createdBy: "Admin",
    updatedAt: new Date(),
    updatedBy: "Admin",
    deletedAt: null,
    deletedBy: null,
  },
];
