/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/jAFWAFAxWCE
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function SectionRegion() {
  return (
    <div className="p-8">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-2xl font-bold text-primary">Other Regions tools</h1>
          <p className="text-muted-foreground">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean commodo.
          </p>
        </div>
        <div className="relative">
          <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input type="search" placeholder="Search tool from other regions" className="pl-8 w-[300px]" />
        </div>
      </div>
      <div className="space-y-6">
        <div>
          <h2 className="text-lg font-bold text-primary">ITALY</h2>
          <div className="grid grid-cols-1 gap-4 mt-2">
            <Button className="bg-primary text-primary-foreground">Italy</Button>
          </div>
        </div>
        <div>
          <h2 className="text-lg font-bold text-primary">DACH</h2>
          <div className="grid grid-cols-2 gap-4 mt-2">
            <Button className="bg-primary text-primary-foreground">Austria</Button>
            <Button className="bg-primary text-primary-foreground">Switzerland</Button>
          </div>
        </div>
        <div>
          <h2 className="text-lg font-bold text-primary">Nordics</h2>
          <div className="grid grid-cols-4 gap-4 mt-2">
            <Button className="bg-primary text-primary-foreground">Denmark</Button>
            <Button className="bg-primary text-primary-foreground">Finland</Button>
            <Button className="bg-primary text-primary-foreground">Norway</Button>
            <Button className="bg-primary text-primary-foreground">Sweden</Button>
          </div>
        </div>
        <div>
          <h2 className="text-lg font-bold text-primary">CSEE</h2>
          <div className="grid grid-cols-4 gap-4 mt-2">
            <Button className="bg-primary text-primary-foreground">Greece</Button>
            <Button className="bg-primary text-primary-foreground">Poland-PeP Group</Button>
            <Button className="bg-primary text-primary-foreground">Poland-P24</Button>
            <Button className="bg-primary text-primary-foreground">Croatia&Slovenia</Button>
            <Button className="bg-primary text-primary-foreground col-span-4 sm:col-span-1">Central Europe</Button>
          </div>
        </div>
      </div>
      <div className="mt-8 flex items-center">
        <p className="text-lg font-bold text-primary">Missing tool?</p>
        <Button className="ml-4 bg-primary text-primary-foreground flex items-center">
          <MailIcon className="mr-2 h-4 w-4" />
          Write us!
        </Button>
      </div>
    </div>
  )
}

function MailIcon(props : any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function SearchIcon(props : any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
