/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Lpibp8te0jk
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import { Card, CardHeader, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"

export function SectionFavourites() {
  return (
    <div className="p-6 space-y-8">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold">Tools</h1>
          <p className="text-muted-foreground">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
          </p>
        </div>
        <div className="relative">
          <SearchIcon className="absolute left-3 top-3 h-5 w-5 text-muted-foreground" />
          <Input type="search" placeholder="Search tool" className="pl-10 w-64" />
        </div>
      </div>
      <div>
        <h2 className="text-2xl font-bold text-blue-600 flex items-center">
          Favourites <StarIcon className="ml-2 h-5 w-5 text-blue-600" />
        </h2>
        <p className="text-blue-600 mt-2 cursor-pointer">+ Add tool</p>
        <div className="flex space-x-4 mt-4">
          <Card className="w-40">
            <CardHeader className="flex justify-between items-center">
              <Badge variant="secondary">Group</Badge>
              <StarIcon className="h-5 w-5 text-blue-600" />
            </CardHeader>
            <CardContent className="flex flex-col items-center">
              <PenToolIcon className="h-12 w-12 text-blue-600" />
              <p className="mt-2 font-semibold">Lorem Ipsum</p>
            </CardContent>
          </Card>
          <Card className="w-40">
            <CardHeader className="flex justify-between items-center">
              <Badge variant="secondary">Group</Badge>
              <StarIcon className="h-5 w-5 text-blue-600" />
            </CardHeader>
            <CardContent className="flex flex-col items-center">
              <PenToolIcon className="h-12 w-12 text-blue-600" />
              <p className="mt-2 font-semibold">Lorem Ipsum</p>
            </CardContent>
          </Card>
          <Card className="w-40">
            <CardHeader className="flex justify-between items-center">
              <Badge variant="secondary">Group</Badge>
              <StarIcon className="h-5 w-5 text-blue-600" />
            </CardHeader>
            <CardContent className="flex flex-col items-center">
              <PenToolIcon className="h-12 w-12 text-blue-600" />
              <p className="mt-2 font-semibold">Lorem Ipsum</p>
            </CardContent>
          </Card>
        </div>
      </div>
      <div>
        <h2 className="text-2xl font-bold text-blue-600">Categories</h2>
        <p className="text-muted-foreground">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <div className="grid grid-cols-2 gap-4 mt-4">
          <Button className="bg-blue-600 text-white">Lorem Ipsum</Button>
          <Button className="bg-blue-400 text-white">Lorem Ipsum</Button>
          <Button className="bg-blue-400 text-white">Lorem Ipsum</Button>
          <Button className="bg-blue-400 text-white">Lorem Ipsum</Button>
        </div>
      </div>
    </div>
  )
}

function PenToolIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15.707 21.293a1 1 0 0 1-1.414 0l-1.586-1.586a1 1 0 0 1 0-1.414l5.586-5.586a1 1 0 0 1 1.414 0l1.586 1.586a1 1 0 0 1 0 1.414z" />
      <path d="m18 13-1.375-6.874a1 1 0 0 0-.746-.776L3.235 2.028a1 1 0 0 0-1.207 1.207L5.35 15.879a1 1 0 0 0 .776.746L13 18" />
      <path d="m2.3 2.3 7.286 7.286" />
      <circle cx="11" cy="11" r="2" />
    </svg>
  )
}


function SearchIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function StarIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
