/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qDzDKrydvdi
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"

export function SectionSearch() {
  return (
    <div className="min-h-screen bg-gray-100">
      <header className="bg-[#3f2a9e] text-white py-4">
        <div className="container mx-auto">
          <h1 className="text-2xl font-bold">Lorem Ipsum</h1>
        </div>
      </header>
      <main className="container mx-auto py-8">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
          {Array.from({ length: 16 }).map((_, index) => (
            <Card key={index} className="relative">
              <div className="absolute top-2 left-2">
                <Badge variant="secondary">{index % 4 === 0 ? "Group" : "Germany"}</Badge>
              </div>
              <div className="absolute top-2 right-2">
                <StarIcon className="w-6 h-6 text-gray-400" />
              </div>
              <CardContent className="flex flex-col items-center justify-center p-4">
                <ImageIcon className="w-16 h-16 text-[#3f2a9e]" />
                <h2 className="mt-4 text-lg font-semibold">Lorem Ipsum</h2>
                <a href="#" className="mt-2 text-blue-600">
                  read more +
                </a>
                <Button variant="outline" className="mt-4">
                  OPEN TOOL
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      </main>
    </div>
  )
}

function ImageIcon(props : any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </svg>
  )
}


function StarIcon(props : any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
