/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wXBbIwK33oD
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { FavouriteIcon } from "./favourite-icon";

export interface ToolMiniatureProps {
  weburl: string;
  title: string;
  badge: string;
  isfavourite: boolean;
  tooglefavourite: () => void;
  onClick: () => void;
}

export function ToolMiniature(props: ToolMiniatureProps) {
  const { title, badge, isfavourite, tooglefavourite, onClick } = props;
  return (
    <Card
      className="w-[200px] h-[200px] m-2 p-4 relative rounded-lg hover:shadow-lg cursor-pointer hover:bg-gray-100"
      onClick={onClick}
    >
      <Badge variant="secondary" className="absolute top-2 left-2">
        {badge}
      </Badge>
      <UserIcon className="w-16 h-16 mx-auto mt-8 mb-4 text-blue-500" />
      <div className="text-center text-lg font-bold overflow-hidden max-h-14 min-h-14">
        {title}
      </div>
      <FavouriteIcon
        onClick={tooglefavourite}
        className="absolute top-2 right-2 w-6 h-6 text-blue-700 cursor-default"
        selected={isfavourite}
      />
    </Card>
  );
}

function UserIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}
