"use client"
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/A7isu8Dzc3T
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { FavouriteIcon } from "./favourite-icon";
export interface ToolLargeProps {
  weburl: string;
  title: string;

  description: string;
  badge: string;
  isfavourite: boolean;
  toogleFavourite: () => void;
  onClick: () => void;
}
export function ToolLarge(props: ToolLargeProps) {
  const {
    title,
    badge,
    isfavourite,
    toogleFavourite: tooglefavourite,
    onClick,
    description,
    weburl,
  } = props;
  return (
    <div className="max-w-md p-4 bg-white rounded-lg shadow-md">
      <div className="flex items-center justify-between">
        <div className="flex items-center">
          <div className="bg-[#00d8ff] text-white px-2 py-1 rounded-md">
            {badge}
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <FavouriteIcon
            onClick={tooglefavourite}
            className="absolute top-2 right-2 w-6 h-6 text-blue-700 cursor-default"
            selected={isfavourite}
          />
          {/* <XIcon className="w-6 h-6 text-blue-600" /> */}
        </div>
      </div>
      <div className="flex flex-col items-center mt-4">
        <ArrowUpIcon className="w-16 h-16 text-blue-600" />
        <div className="mt-4 text-center">
          <h2 className="text-lg font-bold">{title}</h2>
          <p className="text-sm text-gray-600">{description}</p>
        </div>
      </div>
      <div className="grid grid-cols-2 gap-4 mt-4">
        <div className="flex items-center space-x-2">
          <FileIcon className="w-6 h-6 text-red-600" />
          <div>
            <p className="text-sm font-medium">Lorem Ipsum</p>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <FileIcon className="w-6 h-6 text-red-600" />
          <div>
            <p className="text-sm font-medium">Lorem Ipsum dolor sit amet</p>
            <p className="text-xs text-gray-600">Lorem ipsum</p>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <FileIcon className="w-6 h-6 text-red-600" />
          <div>
            <p className="text-sm font-medium">Lorem Ipsum</p>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <GlobeIcon className="w-6 h-6 text-gray-600" />
          <div>
            <p className="text-sm font-medium">Lorem Ipsum</p>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <FileIcon className="w-6 h-6 text-red-600" />
          <div>
            <p className="text-sm font-medium">Lorem Ipsum</p>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <GlobeIcon className="w-6 h-6 text-gray-600" />
          <div>
            <p className="text-sm font-medium">Lorem Ipsum</p>
          </div>
        </div>
      </div>
      <div className="flex justify-center mt-6">
        <Link href={weburl} target="_blank">
          <Button className="bg-blue-600 text-white">OPEN TOOL</Button>
        </Link>
      </div>
    </div>
  );
}

function ArrowUpIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m5 12 7-7 7 7" />
      <path d="M12 19V5" />
    </svg>
  );
}

function FileIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>
  );
}

function GlobeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20" />
      <path d="M2 12h20" />
    </svg>
  );
}

function StarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}

function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
