/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wXBbIwK33oD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export function ToolMiniature() {
  return (
    <Card className="w-[200px] h-[200px] p-4 relative rounded-lg">
      <Badge variant="secondary" className="absolute top-2 left-2">
        Group 123
      </Badge>
      <UserIcon className="w-16 h-16 mx-auto mt-8 mb-4 text-blue-500" />
      <div className="text-center text-lg font-bold">Lorem Ipsum</div>
      <StarIcon className="absolute top-2 right-2 w-6 h-6 text-blue-700 " />
    </Card>
  )
}

function StarIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function UserIcon(props : any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
